compilers:
- compiler:
    environment:
      set:
        LD_LIBRARY_PATH: /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0binutils/x86_64-slc6/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.28-19981/x86_64-slc6-gcc62-opt/lib:EXTRA_LIBS
    extra_rpaths:
    - /cvmfs/sft.cern.ch/lcg/releases/binutils/2.28-19981/x86_64-slc6-gcc62-opt/bin
    - /cvmfs/sft.cern.ch/lcg/releases/binutils/2.28-19981/x86_64-slc6-gcc62-opt/lib
    flags:
     cppflags: -std=c++17
    modules: []
    operating_system: scientificcernslc6
    paths:
      cc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0binutils/x86_64-slc6-gcc7-opt/bin/gcc
      cxx: /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0binutils/x86_64-slc6-gcc7-opt/bin/g++
      f77: /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0binutils/x86_64-slc6-gcc7-opt/bin/gfortran
      fc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/7.3.0binutils/x86_64-slc6-gcc7-opt/bin/gfortran
    spec: gcc@7.3.0
    target: x86_64
